### ISSUE TITLE
Cordova YoutubeVideoPlayer not working

### ISSUE THREAD

**Issue by huynhvantuan** [Glitchbone/CordovaYoutubeVideoPlayer#28]
I create a "Play Youtube" App with PhoneGap(version 6.3.0) , Cordova (version  6.3.1) , simple  load a youtube video by ID.
use Cordova YoutubeVideoPlayer plugin, but not working, Why?
test on android OS  version 6.0.
Thanks in advance.

add to config.xml:
`<plugin name="com.bunkerpalace.cordova.youtubevideoplayer" spec="1.0.1" source="pgb" />
`
Load youtube video when device ready in index.js
`YoutubeVideoPlayer.openVideo('1s96mq8kfzY');`

using build.phonegap.com to build project, but when run has an error:
`An error occurred during the retrieval of the video. This could be due to network issue of YouTube protocols. Please try again later.`

index.js

 ```
var app = {
     initialize: function() {
         this.bindEvents();
     }, bindEvents: function() {
         document.addEventListener('deviceready', this.onDeviceReady, false);
     },   onDeviceReady: function() {
         app.receivedEvent('deviceready');
     },   
     receivedEvent: function(id) {
         var parentElement = document.getElementById(id);
         var listeningElement = parentElement.querySelector('.listening');
         var receivedElement = parentElement.querySelector('.received');
 
         listeningElement.setAttribute('style', 'display:none;');
         receivedElement.setAttribute('style', 'display:block;');
         console.log('Received Event: ' + id);        
         YoutubeVideoPlayer.openVideo('1s96mq8kfzY');
     }
 };
```

index.html
```
<html>
 <head>
     <meta charset="utf-8" />
     <meta name="format-detection" content="telephone=no" />
     <meta name="msapplication-tap-highlight" content="no" />
     <meta name="viewport" content="user-scalable=no, initial-scale=1, maximum-scale=1, minimum-scale=1, width=device-width" /> 
     <link rel="stylesheet" type="text/css" href="css/index.css" />
     <title>Hello World</title>
 </head>
 
 <body>
    <div class="app">
         <h1>PhoneGap</h1>
         <div id="deviceready" class="blink">
             <p class="event listening">Connecting to Device</p>
             <p class="event received">Device is Ready</p>
         </div>         
     </div>
     <script type="text/javascript" src="cordova.js"></script>
     <script type="text/javascript" src="js/index.js"></script>
     <script type="text/javascript">
         app.initialize();
     </script>
 </body>
 </html>
```

config.xml
 ```
<?xml version='1.0' encoding='utf-8'?>
<widget id="com.hd.yu" version="1.0.0" xmlns="http://www.w3.org/ns/widgets" xmlns:gap="http://phonegap.com/ns/1.0">
    <name>YTube2</name>
    <description>
        Hello World sample application that responds to the deviceready event.
    </description>
    <author email="support@phonegap.com" href="http://phonegap.com">
        PhoneGap Team
    </author>
    <content src="index.html" />
    <preference name="DisallowOverscroll" value="true" />
    <preference name="android-minSdkVersion" value="14" />
    <plugin name="cordova-plugin-battery-status" source="npm" spec="~1.1.1" />
    <plugin name="cordova-plugin-camera" source="npm" spec="~2.1.1" />
    <plugin name="cordova-plugin-media-capture" source="npm" spec="~1.2.0" />
    <plugin name="cordova-plugin-console" source="npm" spec="~1.0.2" />
    <plugin name="cordova-plugin-contacts" source="npm" spec="~2.0.1" />
    <plugin name="cordova-plugin-device" source="npm" spec="~1.1.1" />
    <plugin name="cordova-plugin-device-motion" source="npm" spec="~1.2.0" />
    <plugin name="cordova-plugin-device-orientation" source="npm" spec="~1.0.2" />
    <plugin name="cordova-plugin-dialogs" source="npm" spec="~1.2.0" />
    <plugin name="cordova-plugin-file" source="npm" spec="~4.1.1" />
    <plugin name="cordova-plugin-file-transfer" source="npm" spec="~1.5.0" />
    <plugin name="cordova-plugin-geolocation" source="npm" spec="~2.1.0" />
    <plugin name="cordova-plugin-globalization" source="npm" spec="~1.0.3" />
    <plugin name="cordova-plugin-inappbrowser" source="npm" spec="~1.3.0" />
    <plugin name="cordova-plugin-media" source="npm" spec="~2.2.0" />
    <plugin name="cordova-plugin-network-information" source="npm" spec="~1.2.0" />
    <plugin name="cordova-plugin-splashscreen" source="npm" spec="~3.2.1" />
    <plugin name="cordova-plugin-statusbar" source="npm" spec="~2.1.2" />
    <plugin name="cordova-plugin-vibration" source="npm" spec="~2.1.0" />
    <plugin name="cordova-plugin-whitelist" source="npm" spec="~1.2.1" />
    <plugin name="com.bunkerpalace.cordova.youtubevideoplayer" spec="1.0.1" source="pgb" />
    <icon src="icon.png" />
    <platform name="android">
        <icon density="ldpi" src="www/res/icon/android/drawable-ldpi-icon.png" />
        <icon density="mdpi" src="www/res/icon/android/drawable-mdpi-icon.png" />
        <icon density="hdpi" src="www/res/icon/android/drawable-hdpi-icon.png" />
        <icon density="xhdpi" src="www/res/icon/android/drawable-xhdpi-icon.png" />
        <icon density="xxhdpi" src="www/res/icon/android/drawable-xxhdpi-icon.png" />
        <icon density="xxxhdpi" src="www/res/icon/android/drawable-xxxhdpi-icon.png" />
        <splash density="land-ldpi" src="www/res/screen/android/drawable-land-ldpi-screen.png" />
        <splash density="land-mdpi" src="www/res/screen/android/drawable-land-mdpi-screen.png" />
        <splash density="land-hdpi" src="www/res/screen/android/drawable-land-hdpi-screen.png" />
        <splash density="land-xhdpi" src="www/res/screen/android/drawable-land-xhdpi-screen.png" />
        <splash density="land-xxhdpi" src="www/res/screen/android/drawable-land-xxhdpi-screen.png" />
        <splash density="land-xxxhdpi" src="www/res/screen/android/drawable-land-xxxhdpi-screen.png" />
        <splash density="port-ldpi" src="www/res/screen/android/drawable-port-ldpi-screen.png" />
        <splash density="port-mdpi" src="www/res/screen/android/drawable-port-mdpi-screen.png" />
        <splash density="port-hdpi" src="www/res/screen/android/drawable-port-hdpi-screen.png" />
        <splash density="port-xhdpi" src="www/res/screen/android/drawable-port-xhdpi-screen.png" />
        <splash density="port-xxhdpi" src="www/res/screen/android/drawable-port-xxhdpi-screen.png" />
        <splash density="port-xxxhdpi" src="www/res/screen/android/drawable-port-xxxhdpi-screen.png" />
    </platform>
    <platform name="ios">
        <icon height="57" platform="ios" src="www/res/icon/ios/icon.png" width="57" />
        <icon height="114" platform="ios" src="www/res/icon/ios/icon@2x.png" width="114" />
        <icon height="40" platform="ios" src="www/res/icon/ios/icon-40.png" width="40" />
        <icon height="80" platform="ios" src="www/res/icon/ios/icon-40@2x.png" width="80" />
        <icon height="50" platform="ios" src="www/res/icon/ios/icon-50.png" width="50" />
        <icon height="100" platform="ios" src="www/res/icon/ios/icon-50@2x.png" width="100" />
        <icon height="60" platform="ios" src="www/res/icon/ios/icon-60.png" width="60" />
        <icon height="120" platform="ios" src="www/res/icon/ios/icon-60@2x.png" width="120" />
        <icon height="180" platform="ios" src="www/res/icon/ios/icon-60@3x.png" width="180" />
        <icon height="72" platform="ios" src="www/res/icon/ios/icon-72.png" width="72" />
        <icon height="144" platform="ios" src="www/res/icon/ios/icon-72@2x.png" width="144" />
        <icon height="76" platform="ios" src="www/res/icon/ios/icon-76.png" width="76" />
        <icon height="152" platform="ios" src="www/res/icon/ios/icon-76@2x.png" width="152" />
        <icon height="29" platform="ios" src="www/res/icon/ios/icon-small.png" width="29" />
        <icon height="58" platform="ios" src="www/res/icon/ios/icon-small@2x.png" width="58" />
        <icon height="87" platform="ios" src="www/res/icon/ios/icon-small@3x.png" width="87" />
        <splash height="1136" platform="ios" src="www/res/screen/ios/Default-568h@2x~iphone.png" width="640" />
        <splash height="1334" platform="ios" src="www/res/screen/ios/Default-667h.png" width="750" />
        <splash height="2208" platform="ios" src="www/res/screen/ios/Default-736h.png" width="1242" />
        <splash height="1242" platform="ios" src="www/res/screen/ios/Default-Landscape-736h.png" width="2208" />
        <splash height="1536" platform="ios" src="www/res/screen/ios/Default-Landscape@2x~ipad.png" width="2048" />
        <splash height="768" platform="ios" src="www/res/screen/ios/Default-Landscape~ipad.png" width="1024" />
        <splash height="2048" platform="ios" src="www/res/screen/ios/Default-Portrait@2x~ipad.png" width="1536" />
        <splash height="1024" platform="ios" src="www/res/screen/ios/Default-Portrait~ipad.png" width="768" />
        <splash height="960" platform="ios" src="www/res/screen/ios/Default@2x~iphone.png" width="640" />
        <splash height="480" platform="ios" src="www/res/screen/ios/Default~iphone.png" width="320" />
    </platform>
    <platform name="wp8">
        <icon height="99" platform="wp8" src="www/res/icon/wp8/ApplicationIcon.png" width="99" />
        <icon height="159" platform="wp8" src="www/res/icon/wp8/Background.png" width="159" />
        <splash height="1280" platform="wp8" src="www/res/screen/wp8/screen-portrait.jpg" width="768" />
    </platform>
    <platform name="windows">
        <icon height="150" platform="windows" src="www/res/icon/windows/Square150x150Logo.scale-100.png" width="150" />
        <icon height="30" platform="windows" src="www/res/icon/windows/Square30x30Logo.scale-100.png" width="30" />
        <icon height="50" platform="windows" src="www/res/icon/windows/StoreLogo.scale-100.png" width="50" />
        <splash height="300" platform="windows" src="www/res/screen/windows/SplashScreen.scale-100.png" width="620" />
        <icon height="120" platform="windows" src="www/res/icon/windows/StoreLogo.scale-240.png" width="120" />
        <icon height="44" platform="windows" src="www/res/icon/windows/Square44x44Logo.scale-100.png" width="44" />
        <icon height="106" platform="windows" src="www/res/icon/windows/Square44x44Logo.scale-240.png" width="106" />
        <icon height="70" platform="windows" src="www/res/icon/windows/Square70x70Logo.scale-100.png" width="70" />
        <icon height="71" platform="windows" src="www/res/icon/windows/Square71x71Logo.scale-100.png" width="71" />
        <icon height="170" platform="windows" src="www/res/icon/windows/Square71x71Logo.scale-240.png" width="170" />
        <icon height="360" platform="windows" src="www/res/icon/windows/Square150x150Logo.scale-240.png" width="360" />
        <icon height="310" platform="windows" src="www/res/icon/windows/Square310x310Logo.scale-100.png" width="310" />
        <icon height="150" platform="windows" src="www/res/icon/windows/Wide310x150Logo.scale-100.png" width="310" />
        <icon height="360" platform="windows" src="www/res/icon/windows/Wide310x150Logo.scale-240.png" width="744" />
        <splash height="1920" platform="windows" src="www/res/screen/windows/SplashScreenPhone.scale-240.png" width="1152" />
    </platform>
    <access origin="*" />
    <allow-intent href="http://*/*" />
    <allow-intent href="https://*/*" />
    <allow-intent href="tel:*" />
    <allow-intent href="sms:*" />
    <allow-intent href="mailto:*" />
    <allow-intent href="geo:*" />
    <platform name="android">
        <allow-intent href="market:*" />
    </platform>
    <platform name="ios">
        <allow-intent href="itms:*" />
        <allow-intent href="itms-apps:*" />
    </platform>
    <engine name="android" spec="~5.2.2" />
</widget>

```

**Comment by murilosardinha** [comment]
The same here. I forked the project and it doesn't works.

**Comment by selcycer** [comment]
Me too.

**Comment by edmundtfy** [comment]
Me too....

**Comment by edmundtfy** [comment]
`12-22 16:52:53.483 11993-11993/com.ionicframework.iwtk464868 E/MediaPlayer-JNI: JNIMediaPlayerFactory: bIsQCMediaPlayerPresent 0
12-22 16:52:53.483 11993-11993/com.ionicframework.iwtk464868 E/MediaPlayer-JNI: JNIMediaPlayerFactory: bIsQCMediaPlayerPresent 0
12-22 16:52:53.485 11993-11993/com.ionicframework.iwtk464868 W/MediaPlayer: Couldn't open file on client side; trying server side: java.io.FileNotFoundException: No content provider: http%3A%2F%2Fr5---sn-i3beln7k.googlevideo.com%2Fvideoplayback%3Flmt%3D1481949086358337%26itag%3D18%26ip%3D202.126.213.158%26nh%3DIgpwcjA0LmhrZzAxKgkxMjcuMC4wLjE%26pl%3D21%26source%3Dyoutube%26dur%3D167.137%26key%3Dyt6%26id%3Do-AFcOmdTCczWCrRg0zjYVodBC8NqSTkA4kz_YKJqHTAmH%26mn%3Dsn-i3beln7k%26mm%3D31%26mime%3Dvideo%252Fmp4%26upn%3DU4uTASCWTrs%26signature%3D4F33CE002FB8D8423E26833CD302985EEE14F4F4.346A08B5D8DC23508DB88A04DA1C7CF43860C651%26expire%3D1482418373%26initcwndbps%3D2270000%26mv%3Dm%26mt%3D1482396432%26ms%3Dau%26sparams%3Ddur%252Cid%252Cinitcwndbps%252Cip%252Cipbits%252Citag%252Clmt%252Cmime%252Cmm%252Cmn%252Cms%252Cmv%252Cnh%252Cpl%252Cratebypass%252Csource%252Cupn%252Cexpire%26ratebypass%3Dyes%26ipbits%3D0&signature=null
12-22 16:52:53.487 11993-11993/com.ionicframework.iwtk464868 W/VideoView: Unable to open content: http%3A%2F%2Fr5---sn-i3beln7k.googlevideo.com%2Fvideoplayback%3Flmt%3D1481949086358337%26itag%3D18%26ip%3D202.126.213.158%26nh%3DIgpwcjA0LmhrZzAxKgkxMjcuMC4wLjE%26pl%3D21%26source%3Dyoutube%26dur%3D167.137%26key%3Dyt6%26id%3Do-AFcOmdTCczWCrRg0zjYVodBC8NqSTkA4kz_YKJqHTAmH%26mn%3Dsn-i3beln7k%26mm%3D31%26mime%3Dvideo%252Fmp4%26upn%3DU4uTASCWTrs%26signature%3D4F33CE002FB8D8423E26833CD302985EEE14F4F4.346A08B5D8DC23508DB88A04DA1C7CF43860C651%26expire%3D1482418373%26initcwndbps%3D2270000%26mv%3Dm%26mt%3D1482396432%26ms%3Dau%26sparams%3Ddur%252Cid%252Cinitcwndbps%252Cip%252Cipbits%252Citag%252Clmt%252Cmime%252Cmm%252Cmn%252Cms%252Cmv%252Cnh%252Cpl%252Cratebypass%252Csource%252Cupn%252Cexpire%26ratebypass%3Dyes%26ipbits%3D0&signature=null
                                                                          java.io.IOException: setDataSource failed.
                                                                              at android.media.MediaPlayer.setDataSource(MediaPlayer.java:1095)
                                                                              at android.media.MediaPlayer.setDataSource(MediaPlayer.java:1069)
                                                                              at android.media.MediaPlayer.setDataSource(MediaPlayer.java:1023)
                                                                              at android.widget.VideoView.openVideo(VideoView.java:346)
                                                                              at android.widget.VideoView.setVideoURI(VideoView.java:256)
                                                                              at android.widget.VideoView.setVideoURI(VideoView.java:239)
                                                                              at com.keyes.youtube.OpenYouTubePlayerActivity$QueryYouTubeTask.onPostExecute(OpenYouTubePlayerActivity.java:421)
                                                                              at com.keyes.youtube.OpenYouTubePlayerActivity$QueryYouTubeTask.onPostExecute(OpenYouTubePlayerActivity.java:1)
                                                                              at android.os.AsyncTask.finish(AsyncTask.java:651)
                                                                              at android.os.AsyncTask.-wrap1(AsyncTask.java)
                                                                              at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:668)
                                                                              at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                              at android.os.Looper.loop(Looper.java:148)
                                                                              at android.app.ActivityThread.main(ActivityThread.java:5461)
                                                                              at java.lang.reflect.Method.invoke(Native Method)
                                                                              at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                              at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
`

**Comment by edmundtfy** [comment]
```
12-22 16:52:53.483 11993-11993/com.ionicframework.iwtk464868 E/MediaPlayer-JNI: JNIMediaPlayerFactory: bIsQCMediaPlayerPresent 0
12-22 16:52:53.483 11993-11993/com.ionicframework.iwtk464868 E/MediaPlayer-JNI: JNIMediaPlayerFactory: bIsQCMediaPlayerPresent 0
12-22 16:52:53.485 11993-11993/com.ionicframework.iwtk464868 W/MediaPlayer: Couldn't open file on client side; trying server side: java.io.FileNotFoundException: No content provider: http%3A%2F%2Fr5---sn-i3beln7k.googlevideo.com%2Fvideoplayback%3Flmt%3D1481949086358337%26itag%3D18%26ip%3D202.126.213.158%26nh%3DIgpwcjA0LmhrZzAxKgkxMjcuMC4wLjE%26pl%3D21%26source%3Dyoutube%26dur%3D167.137%26key%3Dyt6%26id%3Do-AFcOmdTCczWCrRg0zjYVodBC8NqSTkA4kz_YKJqHTAmH%26mn%3Dsn-i3beln7k%26mm%3D31%26mime%3Dvideo%252Fmp4%26upn%3DU4uTASCWTrs%26signature%3D4F33CE002FB8D8423E26833CD302985EEE14F4F4.346A08B5D8DC23508DB88A04DA1C7CF43860C651%26expire%3D1482418373%26initcwndbps%3D2270000%26mv%3Dm%26mt%3D1482396432%26ms%3Dau%26sparams%3Ddur%252Cid%252Cinitcwndbps%252Cip%252Cipbits%252Citag%252Clmt%252Cmime%252Cmm%252Cmn%252Cms%252Cmv%252Cnh%252Cpl%252Cratebypass%252Csource%252Cupn%252Cexpire%26ratebypass%3Dyes%26ipbits%3D0&signature=null
12-22 16:52:53.487 11993-11993/com.ionicframework.iwtk464868 W/VideoView: Unable to open content: http%3A%2F%2Fr5---sn-i3beln7k.googlevideo.com%2Fvideoplayback%3Flmt%3D1481949086358337%26itag%3D18%26ip%3D202.126.213.158%26nh%3DIgpwcjA0LmhrZzAxKgkxMjcuMC4wLjE%26pl%3D21%26source%3Dyoutube%26dur%3D167.137%26key%3Dyt6%26id%3Do-AFcOmdTCczWCrRg0zjYVodBC8NqSTkA4kz_YKJqHTAmH%26mn%3Dsn-i3beln7k%26mm%3D31%26mime%3Dvideo%252Fmp4%26upn%3DU4uTASCWTrs%26signature%3D4F33CE002FB8D8423E26833CD302985EEE14F4F4.346A08B5D8DC23508DB88A04DA1C7CF43860C651%26expire%3D1482418373%26initcwndbps%3D2270000%26mv%3Dm%26mt%3D1482396432%26ms%3Dau%26sparams%3Ddur%252Cid%252Cinitcwndbps%252Cip%252Cipbits%252Citag%252Clmt%252Cmime%252Cmm%252Cmn%252Cms%252Cmv%252Cnh%252Cpl%252Cratebypass%252Csource%252Cupn%252Cexpire%26ratebypass%3Dyes%26ipbits%3D0&signature=null
                                                                          java.io.IOException: setDataSource failed.
                                                                              at android.media.MediaPlayer.setDataSource(MediaPlayer.java:1095)
                                                                              at android.media.MediaPlayer.setDataSource(MediaPlayer.java:1069)
                                                                              at android.media.MediaPlayer.setDataSource(MediaPlayer.java:1023)
                                                                              at android.widget.VideoView.openVideo(VideoView.java:346)
                                                                              at android.widget.VideoView.setVideoURI(VideoView.java:256)
                                                                              at android.widget.VideoView.setVideoURI(VideoView.java:239)
                                                                              at com.keyes.youtube.OpenYouTubePlayerActivity$QueryYouTubeTask.onPostExecute(OpenYouTubePlayerActivity.java:421)
                                                                              at com.keyes.youtube.OpenYouTubePlayerActivity$QueryYouTubeTask.onPostExecute(OpenYouTubePlayerActivity.java:1)
                                                                              at android.os.AsyncTask.finish(AsyncTask.java:651)
                                                                              at android.os.AsyncTask.-wrap1(AsyncTask.java)
                                                                              at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:668)
                                                                              at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                              at android.os.Looper.loop(Looper.java:148)
                                                                              at android.app.ActivityThread.main(ActivityThread.java:5461)
                                                                              at java.lang.reflect.Method.invoke(Native Method)
                                                                              at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                              at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

```

**Comment by biranchi2018** [comment]
This plugin is still not working. The issue is still opened.

**Comment by FredeHo** [comment]
Did anyone find a solution?

**Comment by diegodotta** [comment]
This fork is working: https://github.com/denisx304/CordovaYoutubeVideoPlayer

**Comment by garyguoli** [comment]
please help....
