### ISSUE TITLE
I can't install the plugin 

### ISSUE THREAD

**Issue by badrshs** [Glitchbone/CordovaYoutubeVideoPlayer#39]
Hi , 
this is my command line 

```
Y:\ionic\4programmer> ionic cordova plugin add https://github.com/Glitchbone/CordovaYoutubeVideoPlayer.git
> cordova plugin add https://github.com/Glitchbone/CordovaYoutubeVideoPlayer.git --save
✖ Running command - failed!

[ERROR] Cordova encountered an error.
        You may get more insight by running the Cordova command above directly.

[ERROR] An error occurred while running cordova plugin add https://github.com/Glitchbone/CordovaYoutubeVideoPlayer.git
        -... (exit code 1):

        Error: Failed to fetch plugin https://github.com/Glitchbone/CordovaYoutubeVideoPlayer.git via registry.
        Probably this is either a connection problem, or plugin spec is incorrect.
        Check your connection and plugin name/version/URL.
        Error: cmd: Command failed with exit code 1 Error output:
        npm WARN addRemoteGit Error: Command failed: git -c core.longpaths=true config --get remote.origin.url
        npm WARN addRemoteGit
        npm WARN addRemoteGit     at ChildProcess.exithandler (child_process.js:211:12)
        npm WARN addRemoteGit     at emitTwo (events.js:106:13)
        npm WARN addRemoteGit     at ChildProcess.emit (events.js:191:7)
        npm WARN addRemoteGit     at maybeClose (internal/child_process.js:885:16)
        npm WARN addRemoteGit     at Socket.<anonymous> (internal/child_process.js:334:11)
        npm WARN addRemoteGit     at emitOne (events.js:96:13)
        npm WARN addRemoteGit     at Socket.emit (events.js:188:7)
        npm WARN addRemoteGit     at Pipe._handle.close [as _onclose] (net.js:501:12)
        npm WARN addRemoteGit  git+https://github.com/Glitchbone/CordovaYoutubeVideoPlayer.git resetting remote
        C:\Users\bader\AppData\Roaming\npm-cache\_git-remotes\git-https-github-com-Glitchbone-CordovaYoutubeVideoPlayer-git-57241653
        because of error: { Error: Command failed: git -c core.longpaths=true config --get remote.origin.url
        npm WARN addRemoteGit
        npm WARN addRemoteGit     at ChildProcess.exithandler (child_process.js:211:12)
        npm WARN addRemoteGit     at emitTwo (events.js:106:13)
        npm WARN addRemoteGit     at ChildProcess.emit (events.js:191:7)
        npm WARN addRemoteGit     at maybeClose (internal/child_process.js:885:16)
        npm WARN addRemoteGit     at Socket.<anonymous> (internal/child_process.js:334:11)
        npm WARN addRemoteGit     at emitOne (events.js:96:13)
        npm WARN addRemoteGit     at Socket.emit (events.js:188:7)
        npm WARN addRemoteGit     at Pipe._handle.close [as _onclose] (net.js:501:12)
        npm WARN addRemoteGit   killed: false,
        npm WARN addRemoteGit   code: 1,
        npm WARN addRemoteGit   signal: null,
        npm WARN addRemoteGit   cmd: 'git -c core.longpaths=true config --get remote.origin.url' }
        npm ERR! git clone --template=C:\Users\bader\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror
        https://github.com/Glitchbone/CordovaYoutubeVideoPlayer.git
        C:\Users\bader\AppData\Roaming\npm-cache\_git-remotes\git-https-github-com-Glitchbone-CordovaYoutubeVideoPlayer-git-57241653:
        Cloning into bare repository
        'C:\Users\bader\AppData\Roaming\npm-cache\_git-remotes\git-https-github-com-Glitchbone-CordovaYoutubeVideoPlayer-git-57241653'...
        npm ERR! git clone --template=C:\Users\bader\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror
        https://github.com/Glitchbone/CordovaYoutubeVideoPlayer.git
        C:\Users\bader\AppData\Roaming\npm-cache\_git-remotes\git-https-github-com-Glitchbone-CordovaYoutubeVideoPlayer-git-57241653:
        fatal: Unable to find remote helper for 'https'
        npm ERR! Windows_NT 10.0.15063
        npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program
        Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
        "https://github.com/Glitchbone/CordovaYoutubeVideoPlayer.git" "--save"
        npm ERR! node v7.2.1
        npm ERR! npm  v3.10.10
        npm ERR! code 128

        npm ERR! Command failed: git -c core.longpaths=true clone
        --template=C:\Users\bader\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror
        https://github.com/Glitchbone/CordovaYoutubeVideoPlayer.git
        C:\Users\bader\AppData\Roaming\npm-cache\_git-remotes\git-https-github-com-Glitchbone-CordovaYoutubeVideoPlayer-git-57241653
        npm ERR! Cloning into bare repository
        'C:\Users\bader\AppData\Roaming\npm-cache\_git-remotes\git-https-github-com-Glitchbone-CordovaYoutubeVideoPlayer-git-57241653'...
        npm ERR! fatal: Unable to find remote helper for 'https'
        npm ERR!
        npm ERR!
        npm ERR! If you need help, you may report this error at:
        npm ERR!     <https://github.com/npm/npm/issues>

        npm ERR! Please include the following file with any support request:
        npm ERR!     Y:\ionic\4programmer\node_modules\npm-debug.log



Y:\ionic\4programmer>
```

any idea why i can't install it ? 

my ionic information

 
global packages:

    @ionic/cli-utils : 1.4.0
    Cordova CLI      : 7.0.1
    Ionic CLI        : 3.4.0

local packages:

    @ionic/app-scripts              : 1.3.7
    @ionic/cli-plugin-cordova       : 1.4.0
    @ionic/cli-plugin-ionic-angular : 1.3.1
    Cordova Platforms               : android 6.2.3
    Ionic Framework                 : ionic-angular 3.4.2

System:

    Node       : v7.2.1
    OS         : Windows 10
    Xcode      : not installed
    ios-deploy : not installed
    ios-sim    : not installed
    npm        : 3.10.10

**Comment by denisx304** [comment]
because the plugin is missing "package.json"

**Comment by diegodotta** [comment]
This fork is working: https://github.com/denisx304/CordovaYoutubeVideoPlayer
